name = "zivana/onchain"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'zivana/onchain'"

[repository]
user = "zivana"
project = "onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
